### ISSUE TITLE
Implement display off on times

### ISSUE THREAD

**Issue by Dinushka95** [Dinushka95/iNotify#5]
need to recode display on and off times in a table and create helper class to access them

**Comment by Dinushka95** [comment]
@chayawijesundara  what column names do we need in the table? are we creating 2 tables or one? Are we calculating the  (total use time = on time - off time ), is this needed in a future, total time?

**Comment by chayawijesundara** [comment]
two tables are already created to save screen on and off times.ua_screenon table saves the screen on time while us_screenoff_table saves the screen off time.
So far total use time is not calculated. for my component i only check whather the screen is on or off when a notification is delivered.
Some times mihitha might need this type of total time

**Comment by Dinushka95** [comment]
@chayawijesundara ok 
@mihithahansani  do you need the total screen on time?

**Comment by chayawijesundara** [comment]
@Dinushka95 there is another "uc_screentime_table "  on which i have no idea  better asking @mihithahansani

**Comment by Dinushka95** [comment]
@chayawijesundara ok. those old prototype implementations will be deleted after, this is implemented

**Comment by chayawijesundara** [comment]
ok
@Dinushka95 u mean all the tables and classes associated with the old standard

**Comment by Dinushka95** [comment]
@chayawijesundara yes

**Comment by mihithahansani** [comment]
yes

**Comment by mihithahansani** [comment]
> @Dinushka95 there is another "uc_screentime_table " on which i have no idea better asking @mihithahansani

I did not creted that table. any thing related to screen time
